force-app/main/default/objects/RecordPickerConditionConfig__mdt/RecordPickerConditionConfig__mdt.object-meta.xml
<CustomObject>
    <description>THis metadata stores information about the record picker condition configurations.</description>
    <label>Record Picker Condition Config</label>
    <pluralLabel>Record Picker Condition Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>This field is a picklist having condition operators.</description>
    <label>Condition Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eq</fullName>
                <default>true</default>
                <label>Equal</label>
            </value>
            <value>
                <fullName>excludes</fullName>
                <label>Excludes</label>
            </value>
            <value>
                <fullName>gt</fullName>
                <label>Greater Than</label>
            </value>
            <value>
                <fullName>gte</fullName>
                <label>Greater Than Equal To</label>
            </value>
            <value>
                <fullName>in</fullName>
                <label>In</label>
            </value>
            <value>
                <fullName>includes</fullName>
                <label>Includes</label>
            </value>
            <value>
                <fullName>lt</fullName>
                <label>Less Than</label>
            </value>
            <value>
                <fullName>lte</fullName>
                <label>Less Than Equal To</label>
            </value>
            <value>
                <fullName>like</fullName>
                <label>Like</label>
            </value>
            <value>
                <fullName>ne</fullName>
                <label>Not Equal</label>
            </value>
            <value>
                <fullName>nin</fullName>
                <label>Not In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/ConditionFieldAPI__c.field-meta.xml
<CustomField>
    <fullName>ConditionFieldAPI__c</fullName>
    <description>Stores the fieldPath value</description>
    <label>ConditionFieldAPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/ConditionValue__c.field-meta.xml
<CustomField>
    <fullName>ConditionValue__c</fullName>
    <description>This represents the value in a condition it can be either a dynamic value or a literal value.</description>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents if the condition value is a dynamic value so that it can be populated via apex during run time</description>
    <label>Is Dynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/IsLiteral__c.field-meta.xml
<CustomField>
    <fullName>IsLiteral__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents if the condition value is a literal value</description>
    <label>Is Literal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/RecordPickerConfig__c.field-meta.xml
<CustomField>
    <fullName>RecordPickerConfig__c</fullName>
    <description>The Condition Config metadata HAS-A Record Picker Configuration</description>
    <label>Record Picker Config</label>
    <referenceTo>RecordPickerConfig__mdt</referenceTo>
    <relationshipLabel>Record Picker Condition Configs</relationshipLabel>
    <relationshipName>RecordPickerConditionConfigs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/RecordPickerConfig__mdt.object-meta.xml
<CustomObject>
    <description>This metadata stores the main config info for a record picker component</description>
    <label>Record Picker Config</label>
    <pluralLabel>Record Picker Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/DisplayFieldName__c.field-meta.xml
<CustomField>
    <fullName>DisplayFieldName__c</fullName>
    <description>This field stores the info as to what should be displayed while records are searched.</description>
    <label>Display Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/DisplaySecondaryFields__c.field-meta.xml
<CustomField>
    <fullName>DisplaySecondaryFields__c</fullName>
    <description>This field accepts a comma seperate field values while will be used to display as secondary fields.</description>
    <label>Display Secondary Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>This field represent the object api name</description>
    <label>Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordPickerService.cls
/**
 * @description       : This Class handles the Fetching Record Picker Configuration
 * @author            : Vamsi Mudaliar
 * @group             : 
 * @last modified on  : 01-11-2024
 * @last modified by  : Vamsi Mudaliar
**/
public with sharing class RecordPickerService {

    //Get Record Picker Setting for provided configuration
	public static RecordPickerWrapper.ObjectInfo getRecordPicker(string metadataName){
        try {
            List<RecordPickerConfig__mdt> mdt = CustomMetaDataDAO.getMetadataConfig(metadataName);
            if(mdt == null || mdt.isEmpty()) {
                // throw new CustomException('No Suitable Configuration Found');
                return null;
            }
            
            RecordPickerWrapper.ObjectInfo objDto = new RecordPickerWrapper.ObjectInfo();
            objDto.objectName = mdt[0].ObjectAPI__c;
            objDto.primaryField = mdt[0].DisplayFieldName__c;
            objDto.secondaryFields = mdt[0].DisplaySecondaryFields__c;

            //Loop all condition for record picker
            List<RecordPickerWrapper.FieldCondition> fields = new List<RecordPickerWrapper.FieldCondition>();
            for(RecordPickerConditionConfig__mdt cm : mdt[0].getSObjects('RecordPickerConditionConfigs__r')) {

                RecordPickerWrapper.FieldCondition fCondition = new RecordPickerWrapper.FieldCondition();
                fCondition.fieldName = String.valueOf(cm.get('ConditionFieldAPI__c'));
                fCondition.condition = String.valueOf(cm.get('Condition__c'));
                fCondition.conditionValue = String.valueOf(cm.get('ConditionValue__c'));
                fCondition.isLiteral = Boolean.valueOf(cm.get('IsLiteral__c'));
                fCondition.isDynamicValue = Boolean.valueOf(cm.get('IsDynamic__c'));
                fields.add(fCondition);
            }
            objDto.conditions = fields;
            return objDto;
        }
        catch(Exception ex) {
            throw new CustomException('Something went Wrong, While fetching Details');
        }
    }


}