force-app/main/default/objects/RecordPickerConditionConfig__mdt/RecordPickerConditionConfig__mdt.object-meta.xml
<CustomObject>
    <description>THis metadata stores information about the record picker condition configurations.</description>
    <label>Record Picker Condition Config</label>
    <pluralLabel>Record Picker Condition Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>This field is a picklist having condition operators.</description>
    <label>Condition Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eq</fullName>
                <default>true</default>
                <label>Equal</label>
            </value>
            <value>
                <fullName>excludes</fullName>
                <label>Excludes</label>
            </value>
            <value>
                <fullName>gt</fullName>
                <label>Greater Than</label>
            </value>
            <value>
                <fullName>gte</fullName>
                <label>Greater Than Equal To</label>
            </value>
            <value>
                <fullName>in</fullName>
                <label>In</label>
            </value>
            <value>
                <fullName>includes</fullName>
                <label>Includes</label>
            </value>
            <value>
                <fullName>lt</fullName>
                <label>Less Than</label>
            </value>
            <value>
                <fullName>lte</fullName>
                <label>Less Than Equal To</label>
            </value>
            <value>
                <fullName>like</fullName>
                <label>Like</label>
            </value>
            <value>
                <fullName>ne</fullName>
                <label>Not Equal</label>
            </value>
            <value>
                <fullName>nin</fullName>
                <label>Not In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/ConditionFieldAPI__c.field-meta.xml
<CustomField>
    <fullName>ConditionFieldAPI__c</fullName>
    <description>Stores the fieldPath value</description>
    <label>ConditionFieldAPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/ConditionValue__c.field-meta.xml
<CustomField>
    <fullName>ConditionValue__c</fullName>
    <description>This represents the value in a condition it can be either a dynamic value or a literal value.</description>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents if the condition value is a dynamic value so that it can be populated via apex during run time</description>
    <label>Is Dynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/IsLiteral__c.field-meta.xml
<CustomField>
    <fullName>IsLiteral__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents if the condition value is a literal value</description>
    <label>Is Literal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordPickerConditionConfig__mdt/fields/RecordPickerConfig__c.field-meta.xml
<CustomField>
    <fullName>RecordPickerConfig__c</fullName>
    <description>The Condition Config metadata HAS-A Record Picker Configuration</description>
    <label>Record Picker Config</label>
    <referenceTo>RecordPickerConfig__mdt</referenceTo>
    <relationshipLabel>Record Picker Condition Configs</relationshipLabel>
    <relationshipName>RecordPickerConditionConfigs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/RecordPickerConfig__mdt.object-meta.xml
<CustomObject>
    <description>This metadata stores the main config info for a record picker component</description>
    <label>Record Picker Config</label>
    <pluralLabel>Record Picker Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/DisplayFieldName__c.field-meta.xml
<CustomField>
    <fullName>DisplayFieldName__c</fullName>
    <description>This field stores the info as to what should be displayed while records are searched.</description>
    <label>Display Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/DisplaySecondaryFields__c.field-meta.xml
<CustomField>
    <fullName>DisplaySecondaryFields__c</fullName>
    <description>This field accepts a comma seperate field values while will be used to display as secondary fields.</description>
    <label>Display Secondary Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordPickerConfig__mdt/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>This field represent the object api name</description>
    <label>Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetaDataDAO.cls
/**
 * @description       : DAO Class for Fetch Metadata Config
 * @author            : Vamsi Mudaliar
 * @group             : MTX Group Inc
 * @last modified on  : 01-10-2024
 * @last modified by  : Vamsi Mudaliar
**/
public with sharing class CustomMetaDataDAO {

    
    public static List<RecordPickerConfig__mdt> getMetadataConfig(string metadataName) {
        return [SELECT Id, ObjectAPI__c, DisplayFieldName__c, DisplaySecondaryFields__c, 
               (SELECT Id, RecordPickerConfig__c, ConditionFieldAPI__c, Condition__c, ConditionValue__c, IsLiteral__c, IsDynamic__c 
                FROM RecordPickerConditionConfigs__r)
                                    FROM RecordPickerConfig__mdt where DeveloperName=:metadataName];   
    }
}